In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv("input/training.csv")
df.head()
df.info()
df.describe()

df.hist(bins=30, figsize=(15, 10))
# for column in df.columns:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8470 entries, 0 to 8469
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           8470 non-null   int64
 1   DeltaR_lab23         8470 non-null   float64
 2   DeltaR_lab45         8470 non-null   float64
 3   Label                8470 non-null   object
 4   lab0_ENDVERTEX_CHI2  8470 non-null   float64
 5   lab0_IPCHI2_OWNPV    8470 non-null   float64
 6   lab0_RFD             8470 non-null   float64
 7   lab0_ptasy_1.50      8470 non-null   float64
 8   lab10_IPCHI2_OWNPV   8470 non-null   float64
 9   lab2_FDCHI2_OWNPV    8470 non-null   float64
 10  lab2_IPCHI2_OWNPV    8470 non-null   float64
 11  lab2_PT              8470 non-null   float64
 12  lab4_ENDVERTEX_CHI2  8470 non-null   float64
 13  lab4_RFD             8470 non-null   float64
 14  lab5_PT              8470 non-null   float64
 15  lab8_PT              8470 non-null   float64
 16  lab9_IPCHI2_OWNPV    8470 non-null   float64
dtypes: float64(15), int64(1), object(1)
memory usage: 1.1+ MB

,Unnamed: 0,DeltaR_lab23,DeltaR_lab45,lab0_ENDVERTEX_CHI2,lab0_IPCHI2_OWNPV,lab0_RFD,lab0_ptasy_1.50,lab10_IPCHI2_OWNPV,lab2_FDCHI2_OWNPV,lab2_IPCHI2_OWNPV,lab2_PT,lab4_ENDVERTEX_CHI2,lab4_RFD,lab5_PT,lab8_PT,lab9_IPCHI2_OWNPV
count,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8.470000e+03,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000,8470.000000
mean,4245.157497,1.810193,0.889499,6.706004,9.133768,1.134324,-0.071313,234.118476,4.272387e+09,4.854642,1833.061149,5.724257,1.335471,383.892247,1688.013974,232.534460
std,3427.932924,1.521709,1.289124,6.086598,7.500108,0.944295,0.414176,337.524966,3.931974e+11,15.537546,1915.660085,5.699013,1.276110,288.391446,1492.300017,334.329666
min,0.000000,0.006584,0.004390,-0.870992,0.000284,0.016111,-0.975606,4.010883,3.296847e-01,0.000347,250.064453,0.003843,0.003523,145.008477,100.656525,3.964398
25%,815.000000,0.491950,0.319659,2.166487,2.267458,0.615819,-0.395385,28.492038,9.912014e+01,0.814581,663.479954,1.726992,0.655176,204.415064,629.859681,29.005210
50%,3718.000000,1.429810,0.538004,4.664304,7.274051,0.884427,-0.128602,104.032370,5.856850e+02,2.114119,1144.117108,3.763266,0.987984,284.581525,1264.547935,101.221764
75%,7253.750000,2.720533,0.829399,9.438129,15.271925,1.331266,0.206244,299.528803,3.092486e+03,5.218917,2250.986834,7.869222,1.588441,449.910760,2253.722965,291.190140
max,11016.000000,6.326523,6.338531,29.972523,25.033038,20.714342,1.000000,3745.062519,3.618698e+13,791.181009,20418.562130,29.827162,33.748080,3407.560076,13012.116997,2976.300003